use_frameworks!

platform :ios, '8.0'

target 'RokidToolsKitTest_Example' do
  pod 'RokidToolsKitTest', :path => '../'

  target 'RokidToolsKitTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
